### ISSUE TITLE
conda package of fredapi will not import

### ISSUE THREAD

**Issue by ralexx** [mortada/fredapi#3]
I wanted to use fredapi in my Anaconda installation so I made a [conda skeleton](http://conda.pydata.org/docs/build_tutorials/pkgs.html#using-conda-skeleton-to-build-from-a-pypi-package) from the PyPI package and then built the skeleton. The conda build script was successful and the new fredapi package tested OK:

```
#truncated
===== testing package: fredapi-0.3.4-py27_0 =====
import: u'fredapi'
===== fredapi-0.3.4-py27_0 OK =====
TEST END: fredapi-0.3.4-py27_0
```

Then I tried installing and this, too, appeared successful.

```
$ conda install --use-local fredapi
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /usr/local/share/anaconda:

The following NEW packages will be INSTALLED:

    fredapi: 0.3.4-py27_0

Linking packages ...
[      COMPLETE      ]|###################################################| 100%

$ conda list fredapi
# packages in environment at /usr/local/share/anaconda:
#
fredapi                   0.3.4                    py27_0
```

But the interpreter in this environment does't recognize the new conda package.

```
Python 2.7.9 |Anaconda 2.2.0 (x86_64)| (default, Dec 15 2014, 10:37:34) 
IPython 3.1.0 -- An enhanced Interactive Python.

In [1]: import fredapi
Traceback (most recent call last):

  File "<ipython-input-1-462d15ed0c18>", line 1, in <module>
    import fredapi

ImportError: No module named fredapi
```

None of conda's troubleshooting [suggestions](http://conda.pydata.org/docs/troubleshooting.html#issue-conda-claims-that-a-package-is-installed-but-it-appears-not-to-be) apply to this case. Do you have any suggestions for properly building a conda package for fredapi?

**Comment by mortada** [comment]
@ralexx are you able to actually run `conda skeleton pypi fredapi`? I'm not actually able to do that. I opened another issue referencing this, hopefully the conda guys will be able to help

**Comment by mortada** [comment]
@ralexx so I can't run `conda skeleton pypi fredapi` but I'm able to just create the recipes from scratch and that seems to work fine. Please see this PR: https://github.com/conda/conda-recipes/pull/304 

those recipe files work for me, including everything from build/install/import

**Comment by mortada** [comment]
I believe this should be resolved now, please reopen if now, thanks

**Comment by benmbrennan** [comment]
I'm still having this issue and what's written in this thread makes no sense to me.  Why isn't there an easy hassle free way to import FRED data into Python?
